### ISSUE TITLE
also cache for logged in users

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/tiny-cache#6]
From #4 

Please explain your change with a positive and a negative example.

**Comment by colinleroy** [comment]
Hi,
I've made this change because it makes it harder to see the gains that the menu cache brings if one has to delog first, or open a private window to test.
Also, the wp_nav_menu functions returns the same menus whether a user is logged in or not ; so it makes it, in my opinion, safer to cache for authenticated users too ; otherwise, a cache flush issue would be invisible to an editor, while affecting visitors.

**Comment by szepeviktor** [comment]
> the wp_nav_menu functions returns the same menus

I have to deny this one.
wp_nav_menu functions are full of filters. Many websites add menu items for logged-in users *only*.

**Comment by colinleroy** [comment]
I understand, I'll remove it!
